return {
    s("lib", {
        t("cc_library("),
        t({"", "    name = \""}),
        i(1, "name"),
        t({"\",", "    srcs = glob([\"**/*.cpp\"]),"}),
        t({"", "    hdrs = glob([\"**/*.hpp\"]),"}),
        t({"", "    deps = [],"}),
        t({"", "    visibility = [\""}),
        i(2, "//visibility:public"),
        t({"\"],"}),
        t({"", ")"}),
    }),
    s("libandtest", {
        t("cc_library("),
        t({"", "    name = \""}),
        i(1, "name"),
        t({"\",", "    srcs = [\""}),
        rep(1),
        t({".cpp\"],", "    hdrs = [\""}),
        rep(1),
        t({".hpp\"],", "    deps = [],",}),
        t({"", "    visibility = [\""}),
        i(2, "//visibility:public"),
        t({"\"],"}),
        t({"", ")", "", ""}),
        t({"cc_test(", "    name = \""}),
        rep(1),
        t({"_test\",","",}),
        t({"    size = \""}),
        i(3, "small"),
        t({"\",", ""}),
        t({"    srcs = [\""}),
        rep(1),
        t({".t.cpp\"],", "    deps = [\":",}),
        rep(1),
        t({"\"],", ")"}),
    }),
    s("test", {
        t("cc_test("),
        t({"", "    name = \""}),
        i(1, "name"),
        t({"_test\",", "", }),
        t({"    size = \""}),
        i(3, "small"),
        t({"\",", ""}),
        t({"    srcs = [\""}),
        rep(1),
        t({".t.cpp\"],", "    deps = [\":",}),
        rep(1),
        t({"\"],", ")"}),
    }),
    s("bin", {
        t("cc_binary("),
        t({"", "    name = \""}),
        i(1, "name"),
        t({"\",", "    srcs = [\""}),
        rep(1),
        t({".cpp\"],", "    deps = [],",}),
        t({"", "    visibility = [\""}),
        i(2, "//visibility:public"),
        t({"\"],"}),
        t({"", ")"}),
    }),
    s("depgtest", {
        t({"\"@googletest//:gtest\",", ""}),
        t({"\"@googletest//:gtest_main\",", ""}),
    }),
}

